INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("baseball", "sport", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("tables", "furniture", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("phones", "electronics", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("chairs", "furniture", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("flares", "explosives", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("fireworks", "explosives", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("tin", "tings", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("more tings", "tings", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("even more tings", "tings", 1000, "01/05/2019", "20/06/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("fairy lights", "lights", 1000, "01/05/2019", "20/06/2019");

INSERT INTO users (name, age) VALUES ("a", 5);
INSERT INTO users (name, age) VALUES ("b", 5);
INSERT INTO users (name, age) VALUES ("c", 51);
INSERT INTO users (name, age) VALUES ("cee", 41);
INSERT INTO users (name, age) VALUES ("e", 11);
INSERT INTO users (name, age) VALUES ("f", 21);
INSERT INTO users (name, age) VALUES ("g", 31);
INSERT INTO users (name, age) VALUES ("o", 41);
INSERT INTO users (name, age) VALUES ("p", 11);
INSERT INTO users (name, age) VALUES ("so", 15);
INSERT INTO users (name, age) VALUES ("sasake", 125);
INSERT INTO users (name, age) VALUES ("sas", 15);
INSERT INTO users (name, age) VALUES ("mas", 11);
INSERT INTO users (name, age) VALUES ("h", 11);
INSERT INTO users (name, age) VALUES ("hi", 115);
INSERT INTO users (name, age) VALUES ("ii", 11);
INSERT INTO users (name, age) VALUES ("ij", 15);
INSERT INTO users (name, age) VALUES ("j", 16);
INSERT INTO users (name, age) VALUES ("k", 12);
INSERT INTO users (name, age) VALUES ("l", 18);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (6000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 17, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (7000, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2400, 18, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2450, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2500, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5900, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 7, 2);
